# Ultralytics 🚀 - AGPL-3.0 License https://ultralytics.com/license
# Ultralytics Actions https://github.com/ultralytics/actions
# This workflow automatically formats code and documentation in PRs to official Ultralytics standards

name: Ultralytics Actions

on:
  issues:
    types: [opened]
  discussion:
    types: [created]
  pull_request:
    branches: [main]
    types: [opened, closed, synchronize, review_requested]

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ultralytics Formatting
        uses: ultralytics/actions@main
        with:
          token: ${{ secrets._GITHUB_TOKEN }}
          labels: true # autolabel issues and PRs
          python: true # format Python code and docstrings
          prettier: true # format YAML, JSON, Markdown and CSS
          spelling: true # check spelling
          links: false # check broken links
          summary: true # print PR summary with GPT4o (requires 'openai_api_key')
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

  CLA:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Run Ultralytics CLA Check
        uses: ultralytics/actions/cla@cla-branch
        with:
          github-token: ${{ secrets._GITHUB_TOKEN }}
          cla_repository: 'ultralytics/cla'
          cla_branch: 'main'
          cla_signatures_path: 'signatures/version1/cla.json'
          cla_document_url: 'https://docs.ultralytics.com/help/CLA'
          allowlist: 'dependabot[bot],github-actions,bot*'
          sign_comment: 'I have read the CLA Document and I sign the CLA'
          allsigned_comment: 'All Contributors have signed the CLA. ✅'
